---
- hosts: 192.168.1.143
  sudo: yes
  tasks:
  - copy:
       src: /home/sonal/mayank/ansible/cfg2html-1.79-1.el7.rf.noarch.rpm
       dest: /home/sonal/mayank/
       mode: 777
  - name: package
    yum:
       name: /home/sonal/mayank/cfg2html-1.79-1.el7.rf.noarch.rpm
       state: present
  - name:
    command: sh cfg2html arg1
    args:
      chdir: /usr/bin/
 
  
   
